In [1]:
!pip install opencv-python
import numpy as np
import cv2 as cv
src =cv.imread("C:\\Users\\CEMRE\\Pictures\\img\\left.jpg")

In [2]:
print(src.shape) #görüntünün boyutunu alma 

(1152, 985, 3)


In [3]:
gray = cv.cvtColor(src,cv.COLOR_BGR2GRAY)
cv.imshow("gray",gray)
cv.waitKey(1)

-1

In [4]:
print(gray.shape)

(1152, 985)


In [5]:
print(gray)

[[168 169 169 ... 202 201 200]
 [170 171 171 ... 199 197 194]
 [171 171 172 ... 198 193 194]
 ...
 [121 121 120 ...  41  40  41]
 [117 117 117 ...  42  42  39]
 [116 115 115 ...  41  41  38]]


In [6]:
gray =np.float32(gray)
print(gray)

[[168. 169. 169. ... 202. 201. 200.]
 [170. 171. 171. ... 199. 197. 194.]
 [171. 171. 172. ... 198. 193. 194.]
 ...
 [121. 121. 120. ...  41.  40.  41.]
 [117. 117. 117. ...  42.  42.  39.]
 [116. 115. 115. ...  41.  41.  38.]]


NORM_MINMAX

In [7]:
min_value,max_value,min_loc,max_loc =cv.minMaxLoc(gray)
print("min_value: %.2f,max_value: %.2f" % (min_value,max_value)) #ortalama

min_value: 0.00,max_value: 255.00


In [8]:
means,stddev = cv.meanStdDev(gray)
print("mean: %.2f, stddev: %.2f"% (means,stddev)) #standart sapma 

mean: 124.24, stddev: 61.60


In [9]:
dst=np.zeros(gray.shape,dtype=np.float32)
cv.normalize(gray, dst=dst, alpha=0,beta=1.0,norm_type=cv.NORM_MINMAX)
print(dst)

[[0.65882355 0.6627451  0.6627451  ... 0.79215693 0.78823537 0.7843138 ]
 [0.6666667  0.67058825 0.67058825 ... 0.7803922  0.7725491  0.7607844 ]
 [0.67058825 0.67058825 0.6745098  ... 0.77647066 0.7568628  0.7607844 ]
 ...
 [0.47450984 0.47450984 0.47058827 ... 0.16078432 0.15686275 0.16078432]
 [0.45882356 0.45882356 0.45882356 ... 0.16470589 0.16470589 0.15294118]
 [0.454902   0.45098042 0.45098042 ... 0.16078432 0.16078432 0.14901961]]


In [10]:
cv.imshow("NORM_MINMAX",dst)
cv.waitKey(1)

-1

In [11]:
min_value,max_value,min_loc,max_loc =cv.minMaxLoc(dst)
print("min_value: %.2f,max_value: %.2f" % (min_value,max_value)) #dönüştürmüş olduğumuz formun ort 

min_value: 0.00,max_value: 1.00


In [12]:
means,stddev = cv.meanStdDev(dst)
print("mean: %.2f, stddev: %.2f"% (means,stddev))

mean: 0.49, stddev: 0.24


NORM_INF

In [15]:
dst=np.zeros(gray.shape,dtype=np.float32)
cv.normalize(gray,dst=dst,alpha=1.0,beta=0,norm_type=cv.NORM_INF)
print(dst)


[[0.65882355 0.6627451  0.6627451  ... 0.79215693 0.78823537 0.7843138 ]
 [0.6666667  0.67058825 0.67058825 ... 0.7803922  0.7725491  0.7607844 ]
 [0.67058825 0.67058825 0.6745098  ... 0.77647066 0.7568628  0.7607844 ]
 ...
 [0.47450984 0.47450984 0.47058827 ... 0.16078432 0.15686275 0.16078432]
 [0.45882356 0.45882356 0.45882356 ... 0.16470589 0.16470589 0.15294118]
 [0.454902   0.45098042 0.45098042 ... 0.16078432 0.16078432 0.14901961]]


In [17]:
cv.imshow("NORM_INF",np.uint8(dst*255))
cv.waitKey(1)

-1

NORM_L1

In [19]:
dst=np.zeros(gray.shape,dtype=np.float32)
cv.normalize(gray,dst=dst,alpha=1.0,beta=0,norm_type=cv.NORM_L1)
print(dst)
cv.imshow("NORM_L1",np.uint8(dst*10000000))
cv.waitKey(1)

[[1.1917203e-06 1.1988138e-06 1.1988138e-06 ... 1.4329019e-06
  1.4258083e-06 1.4187146e-06]
 [1.2059074e-06 1.2130010e-06 1.2130010e-06 ... 1.4116210e-06
  1.3974339e-06 1.3761533e-06]
 [1.2130010e-06 1.2130010e-06 1.2200946e-06 ... 1.4045276e-06
  1.3690596e-06 1.3761533e-06]
 ...
 [8.5832238e-07 8.5832238e-07 8.5122878e-07 ... 2.9083651e-07
  2.8374293e-07 2.9083651e-07]
 [8.2994808e-07 8.2994808e-07 8.2994808e-07 ... 2.9793009e-07
  2.9793009e-07 2.7664936e-07]
 [8.2285447e-07 8.1576093e-07 8.1576093e-07 ... 2.9083651e-07
  2.9083651e-07 2.6955578e-07]]


-1

NORM_L2

In [20]:
dst=np.zeros(gray.shape,dtype=np.float32)
cv.normalize(gray,dst=dst,alpha=1.0,beta=0,norm_type=cv.NORM_L2)
print(dst)
cv.imshow("NORM_L2",np.uint8(dst*10000))
cv.waitKey(1)

[[0.00113734 0.0011441  0.0011441  ... 0.00136751 0.00136074 0.00135397]
 [0.00115087 0.00115764 0.00115764 ... 0.0013472  0.00133366 0.00131335]
 [0.00115764 0.00115764 0.00116441 ... 0.00134043 0.00130658 0.00131335]
 ...
 [0.00081915 0.00081915 0.00081238 ... 0.00027756 0.00027079 0.00027756]
 [0.00079207 0.00079207 0.00079207 ... 0.00028433 0.00028433 0.00026402]
 [0.0007853  0.00077853 0.00077853 ... 0.00027756 0.00027756 0.00025725]]


-1

In [21]:
cv.destroyAllWindows()